version: "3.7"

services:
  api:
    container_name: tm-api
    build:
      context: api
      network: host
    ports:
      - "3333:3333"
    network_mode: host

  site:
    container_name: tm-site
    build:
      context: site
      network: host
    ports:
      - "3000:3000"
    network_mode: host

  rendertron:
    container_name: tm-rendertron
    build:
      context: rendertron
      network: host
    ports:
      - "8000:8000"
    network_mode: host
    volumes:
      - rendertron-cache:/rendertron-cache:rw

volumes:
  rendertron-cache:
