#!/bin/bash

__dirname=$(dirname "$(realpath "$0")")
rootDir="${__dirname}/.."

PS4="\033[0;32m> \033[0m"
set -o xtrace -e

rm -rf "${rootDir}/static/site"

rm -rf /tmp/talentmaker-site
git clone https://github.com/talentmaker/site /tmp/talentmaker-site

cd /tmp/talentmaker-site || exit 1

pnpm install
pnpm build
rm -rf node_modules .git

cd "$__dirname" || exit 1

mv /tmp/talentmaker-site/build "${rootDir}/site/static/site"
