#!/bin/bash

__dirname=$(dirname "$0")
rootDir="${__dirname}/.."

PS4='\033[0;32m> \033[0m'
set -o xtrace -e

docker build -t rendertron "${rootDir}/rendertron"

docker run -p 8000:8000 --network=host -it rendertron
